### ISSUE TITLE
Autowired e dica

### ISSUE THREAD

**Issue by arthurs159** [FelipeSdsilva/gameStoreMafel#1]
Eai Felipe, olhando seu projeto,tem algumas coisas que dariam para fazer um pouquinho diferente, não que estejam erradas, mas é apenas outra forma de fazer.

O Autowired, você poderia retira-lo e adicionar um construtor lá no service e também no controller, se usar lombok fica ainda mais fácil hehe, tem algumas vantagens em utilizar a injeção dessa forma, mas nada que vai fazer uma super diferença em performance nem nada.

Vejo também que você da volta pra dar o retorno quando você faz o findAll sendo que daria pra fazer isso em uma linha só, deixando o código mais simples
![image](https://user-images.githubusercontent.com/77133022/202863551-11505773-49ea-4b64-b393-d0d6cad3cd7e.png)
Deixando assim, por exemplo:
![image](https://user-images.githubusercontent.com/77133022/202863589-258b9a05-1ef2-43cb-90a6-1c0d7402cee2.png)

São coisas simples mas que ajudam a deixar o código um pouco melhor, saca? mas no final é só uma outra forma de fazer já que o seu código está funcionando!!!  : )

**Comment by FelipeSdsilva** [comment]
Que isso agradeço imensamente você por me ensinar e me dar esse feedbackl para minha pessoa não tem coisa melhor do que melhorar o código e saber aceitar que temos muito a melhorar a cada dia mais.

Já ouvi falar do Lombok mas nunca mais usei

Agradelo de coração  por ser tão atencioso com o meu código e um grande tutor de Java.
